config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'members#index'
  resources :members do
    collection do
      get "search", to: "members#search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_members, dependent: :destroy
  has_many :members, through: :game_members, dependent: :destroy

  validates :place, :event_date, presence: true
end

app/models/game_member.rb
class GameMember < ApplicationRecord
  belongs_to :game
  belongs_to :member

  scope :win, -> { where(is_winner: true) }
  scope :lose, -> { where(is_winner: false) }
  validate :check_members_length

  def check_members_length
    errors.add("Members can not be added more than 2") if self.game.game_members.count >= 2
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :game_members, dependent: :destroy
  has_many :games, through: :game_members, dependent: :destroy

  validates :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, uniqueness: true

  after_create :add_joining_date

  def add_joining_date
    self.update(joining_date: Date.today)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :find_member, only: %i[edit update show]
		
  def index
    # 10 members records who played minimum 5 matches
    @members = get_members
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      flash[:success] = 'Member created successfully'
      redirect_to members_path
    else
      render :new
    end
  end

  def show
    game_members = @member.game_members
    @average_score = game_members&.present? ? game_members&.pluck(:score).sum / game_members&.count : 0
    @win_matches = game_members&.win.count
    @lose_matches = game_members&.lose.count
    game_members_score =  game_members&.select(:score, :game_id)
    @highest_score = game_members_score.collect(&:score).max || 0
    partner_player(game_members_score) if game_members.present?
  end

  def edit; end
		
  def update
    if @member.update(member_params)
      flash[:success] = 'Member updated successfully!'
      redirect_to members_path
    else
      render :edit
    end
  end

  def search
    # members = Member.joins(:game_members).select('members.*, AVG(game_members.score) AS members_avg_score').group("members.id").having("count(game_members.id) >= ?",5).order('members_avg_score DESC').limit(10)
    @members = get_members.where('name LIKE ? ', "%#{params[:search]}%")
  end
  private

  def get_members
    Member.joins(:game_members).select('members.*, AVG(game_members.score) AS members_avg_score').group("members.id").having("count(game_members.id) >= ?",5).order('members_avg_score DESC').limit(10)
  end

  def member_params
    params.require(:member).permit(:name, :email, :phone_number)
  end

  def find_member
    @member = Member.find_by_id(params[:id])
    redirect_to root_path unless @member.present?
  end

  def partner_player(game_members_score)
    game = game_members_score.find_by(score: @highest_score).game
    @partner = game.game_members.where.not(member_id:  @member.id).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def round_value(score)
    score.round(2)
  end
end

app/helpers/game_members_helper.rb
module GameMembersHelper
  def member_name(partner)
    partner.member&.name? ? partner.member&.name : partner.member.email
  end

  def game_place(partner)
    partner.game&.place
  end

  def event_date(partner)
    partner.game&.event_date
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scrabble</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container mt-5'>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h5.modal-title
      = (params[:action] == 'new' ? 'Add Member' : 'Edit Member')
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
    .modal-body
      .row
        .col-sm-12
          .card-body
            = form_with model: @member do |form|
              .form-group.m-t-40.row
                = form.label :name, 'Name:'
                = form.text_field :name, class:'form-control'

              .form-group.m-t-40.row
                = form.label :email, 'Email:'
                = form.text_field :email, class:'form-control'

              .form-group.m-t-40.row
                = form.label :phone_number, 'Phone Number:'
                = form.text_field :phone_number, class:'form-control'

              .form-group.m-t-40.row
                .col-md-12
                  .text-center
                    = form.submit class: 'btn btn-success'


:javascript
  $('.close').click(function(){
    $('.modal').hide();
  });

app/views/members/_member.html.haml
%td
  = member.name
%td
  = member.email
%td
  = member.phone_number
%td
  = member.joining_date
%td
  = round_value(member.members_avg_score)
%td
  = link_to member_path(member) do
    %i.fa.fa-eye
  |
  = link_to edit_member_path(member), remote: true do
    %i.fa.fa-edit

app/views/members/_member_listing.html.haml
- members.each do |member|
  %tr
    = render 'member', member: member

app/views/members/edit.js.erb
$('.modal').html('<%= escape_javascript(render "form") %>');
$('.modal').show();

app/views/members/index.html.haml
= form_with url: search_members_path, local: false ,method: 'get' do |form|
  .d-flex.mb-5
    = form.text_field :search, placeholder: 'Search', class:'form-control'
    = form.submit 'search', class: 'btn btn-success'
%table.table
  %thead.thead-dark
    %tr
      %th Name
      %th Email
      %th Phone Number
      %th Joining Date
      %th Average Score
      %th Action
  %tbody#product_listing
    = render 'member_listing', members: @members
.modal

= link_to 'Add member', new_member_path, remote: true, class: 'btn btn-warning'

app/views/members/new.js.erb
$('.modal').html('<%= escape_javascript(render "form") %>');
$('.modal').show();

app/views/members/search.js.erb
$('#product_listing').html("<%= j(render partial: 'member_listing', locals: { members: @members }) %>")

app/views/members/show.html.haml
%h1 
  = "#{@member.name} Details"

.row
  .font-weight-bold.col-sm-3
    Client Name:
  .col-sm-9
    = @member.name

.row
  .font-weight-bold.col-sm-3
    Email:
  .col-sm-9
    = @member.email

.row
  .font-weight-bold.col-sm-3
    Contact Address:
  .col-sm-9
    = @member.phone_number
.row
  .font-weight-bold.col-sm-3
    Joining Date:
  .col-sm-9
    = @member.joining_date

.row
  .font-weight-bold.col-sm-3
    Total Win Matches:
  .col-sm-9
    = @win_matches

.row
  .font-weight-bold.col-sm-3
    Total Lost Matches:
  .col-sm-9
    = @lose_matches

.row
  .font-weight-bold.col-sm-3
    Average Score:
  .col-sm-9
    = round_value(@average_score)

.row
  - if @partner
    .font-weight-bold.col-sm-3
      Highest Score:
    .col-sm-9
      = "#{@highest_score} against"
      = link_to member_name(@partner), member_path(@partner.member)
      = "At #{game_place(@partner)} On #{event_date(@partner)}" 
  - else
    .font-weight-bold.col-sm-3
      Highest Score:
    .col-sm-9
      = @highest_score
.modal
= link_to 'Back', members_path, class: 'btn btn-warning'
= link_to 'Add member', new_member_path, remote: true, class: 'btn btn-success'